### ISSUE TITLE
"Testing a Futuristic Full-Stack JavaScript App... with JavaScript" code & article

### ISSUE THREAD

**Issue by rnicholus** [Widen/fullstack-react#3]
I'm considering a follow-up article to ["The Future of Web Development - React, Falcor, and ES6"](http://engineering.widen.com/blog/future-of-the-web-react-falcor/). This one will cover testing all aspects of this simple application in an automated fashion. 

Here's what I plan to do to support a second article:

Client-side unit tests:
- [x] Pull in Karma, Jasmine 2, PhantomJS 1, and babel-plugin-rewire.
- [x] Write client-side unit tests for all React components.
- [x] Hook into npm test script.

Server-side unit tests:
- [x] Using existing Jasmine 2 library in node environment. Pull in rewire.
- [x] Write server-side unit tests for all Falcor routes.
- [x] Hook into npm test script.

Automated browser-based integration tests:
- [x] Use Jasmine to write tests. Pull in webdriverio.
- [x] Write integration tests for initial render & adding a new name
- [x] Run locally using Firefox + hook into npm test script

Cross-browser testing:
- [x] Use ~~SauceLabs~~ BrowserStack to run client-side unit tests and webdriver integration tests against a few different browsers.

Continuous Integration:
- [x] w/ Travis

- [x] article
- [x] merge test code into master as v2.0

**Comment by yconoclast** [comment]
would you be interested in have a structure like this?


![Structure](https://cloud.githubusercontent.com/assets/4692941/10564741/1d07f40a-75b7-11e5-915b-412cbd092c42.png)

* Have a components folder
* Each module has a package.json

You can take a look in my branch https://github.com/yconoclast/fullstack-react/tree/mine

**Comment by rnicholus** [comment]
The current structure was good enough for my first article, but, as you have noticed, it _definitely_ could use some more structure. This becomes more of a necessity as I write up code for the testing follow-up article. I think your idea of creating a components directory is a good one, along with subdirectories for each component along with a corresponding package.json. If we planned to push each of these components to npm as standalone libraries, your approach would seem to make that pretty easy. I really like this suggestion, and I'm going to keep it in mind for other projects I'm working on, as I've always struggled with a way to easily separate standalone components such that they can be published separately without creating a separate git repository for each of them. I would say that the only components that need their own package.json are those that should be published, and then it would be appropriate to remove the `private: true` property.

My goal is to keep this repo as simple as reasonably possible, so that everything is simple to explain and immediately applicable. That said, I think I'm going to stick with one main package.json file. But, I _do_ plan to reorganize the code, and expect to use the following structure:

- [ ] All client-side code moves into either an "app" or "components" directory, as you have suggested
- [ ] server.js is split up a bit, with Falcor routes going into their own exported module file, and the backing data source (a JavaScript object) in its own exportable module file as well. This will make it _much_ easier to test the Falcor routes. All of these files will be moved to a "server" directory.
- [ ] All configuration files will be moved into a "config" directory.
- [ ] A "test" subdirectory inside of the "components" dir, and another in the "server" dir. As you might expect, the automated tests will live here.

I haven't decided where the integration (webdriver) tests should live. Any suggestions?

**Comment by rnicholus** [comment]
All of the code for this next article, currently staged in the [testing branch](https://github.com/Widen/fullstack-react/tree/testing), is complete. I'll start working on the article next.

**Comment by skvale** [comment]
I'm curious what error you are looking to get around here?

**Comment by rnicholus** [comment]
@skvale When running the server in Travis, neither SauceLabs nor Browserstack VMs are able to connect to the running server, even with the appropriate tunnel in place. The issue is not reproducible outside of Travis (with server & tunnel running locally).

**Comment by rnicholus** [comment]
Finally fixed. Mostly caused by an error on my end - index.html was moved and removed from source control accidentally as part of refactoring the structure of the folders.

**Comment by rnicholus** [comment]
Code is complete, as is the article. Published to http://engineering.widen.com/blog/testing-future-web-stack/.
