### ISSUE TITLE
Falcor with Rx

### ISSUE THREAD

**Issue by almasakchabayev** [Widen/fullstack-react#8]
Hello, Thanks for sharing this resource. Could you also post some examples using falcor, react and rx. Or may be give directions on how to make them work, then I can implement an example and share.

**Comment by rnicholus** [comment]
Rx is out of scope here, but there is already code that makes use of Falcor and React.

**Comment by almasakchabayev** [comment]
yes, but all the examples use Promises not Observables...

**Comment by rnicholus** [comment]
That's true. I don't see any reason to _not_ use Promises. As I said, that is out of scope here, and I have no plans to integrate Rx into the examples.

**Comment by almasakchabayev** [comment]
@rnicholus I wanted to create a simple todo app, but  I am new to both observables and falcor, so my implementation looks weird I just make stuff work and not sure whether it is supposed to be that way. No resources on this topic either... :( Anyways thanks for quick responses. Your examples were really helpfull

**Comment by rnicholus** [comment]
Thanks for the kind words. My suggestion is to use Promises, as this is currently the standardized way of dealing with asynchronous operations.

**Comment by almasakchabayev** [comment]
@rnicholus So many benefits from observables though. If you are familiar with it, may be you can have a look at my code? :)

**Comment by rnicholus** [comment]
Perhaps you can list the benefits of Observables over Promises in this context? Even better, post a comment on the blog so we can discuss there.

**Comment by almasakchabayev** [comment]
@rnicholus well I mean general benefits of FRP, I do not think I have enough knowledge to argue about it. But it just feels more natural for me and easier to reason about and I do not need to learn framework after framework and choose between all the flux implementations. But it is just my opinion though :)

**Comment by rnicholus** [comment]
[Promises are part of ECMAScript 6/2015](http://www.ecma-international.org/ecma-262/6.0/#sec-promise-objects), not part of a framework or library. They are fairly straightoward to use, and the core syntax is the same regardless of the library that includes them as part of an API. Conversely, Observables are not part of any formal specification and are, as a result, library-specific. Unless you can articulate compelling reasons to use Observables, I would stick to a standardized solution instead.

**Comment by rnicholus** [comment]
I should add that the `Promise` specification in ES6 paves the way for other standards, such as the async functions proposal, [which is currently a stage 3 draft](http://tc39.github.io/ecmascript-asyncawait/), and, as a result, is likely to be part of ECMAScript 7. Async functions make it even easier to deal with promises.
